services:
  postgres:
    image: postgres:16
    container_name: crud-assign-postgres
    environment:
      POSTGRES_DB: CRUD_db
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
